using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using MassSpectrometry;
using Readers;

namespace MetaPAL.Models;

[Table("DataFiles")]
public class DataFile
{
    [Key]
    public int Id { get; set; } //autogenerated unique id

    [ForeignKey("Experiment")]
    public int ExperimentId { get; set; }

    public string? FileNameWithoutExtension { get; set; }

    public virtual List<SampleMetaData> ListSampleMetaData { get; set; }

    // Commented out due to issue with loading the test mzml files
    //public virtual List<MsDataScanModel> DataScans { get; set; }

    public virtual Experiment Experiment { get; set; }
    public virtual List<SpectrumMatch>? SpectrumMatches { get; set; }

    public static DataFile FromMsDataFile(MsDataFile msDataFile, int experimentId, List<SampleMetaData> metaData = null)
    {
        DataFile dataFile = new DataFile();
        dataFile.ExperimentId = experimentId;
        dataFile.FileNameWithoutExtension = Path.GetFileNameWithoutExtension(msDataFile.FilePath);
        dataFile.ListSampleMetaData = metaData ?? new List<SampleMetaData>();

        // Commented out due to issue with loading the test mzml files
        //dataFile.DataScans = msDataFile.GetMsDataScans()
        //    .Select(MsDataScanModel.GetModelFromMsDataScan)
        //    .ToList();
        return dataFile;
    }

    public static DataFile FromFilePath(string filePath, int experimentId, List<SampleMetaData> metaData = null)
    {
        var msDataFile = MsDataFileReader.GetDataFile(filePath);
        return FromMsDataFile(msDataFile, experimentId, metaData);
    }
}