using System.ComponentModel.DataAnnotations;

namespace MetaPAL.Models
{
    public class ExperimentMetaData
    {
        [Key]
        public int Id { get; set; } //autogenerated unique id
        string? Organism { get; set; }
        string? Description { get; set; }
        string? SampleProcessingProtocol { get; set; }
        string? DataProcessingProtocol { get; set; }
        string? PublicationDOI { get; set; }
        string? PublicationTitle { get; set; }
        string? SubmissionContact { get; set; }
    }
}
