using MassSpectrometry;
using Microsoft.CodeAnalysis;
using System;
using ThermoFisher.CommonCore.Data.Business;

namespace MetaPAL.Models
{
    public class MsDataScanModel
    {
        /// <summary>
        /// id: MS:1000525
        /// name: spectrum representation
        /// def: "Way in which the spectrum is represented, either with regularly spaced data points or with a list of centroided peaks." [PSI: MS]
        /// relationship: part_of MS:1000442 ! spectrum
        /// </summary>
        public enum SpectrumRepresentationType
        {
            // id: MS:1000127
            // name: centroid spectrum
            // def: "Processing of profile data to produce spectra that contains discrete peaks of zero width. Often used to reduce the size of dataset." [PSI: MS]
            // synonym: "Discrete Mass Spectrum" EXACT []
            // is_a: MS:1000525 ! spectrum representation
            Centroid,
            // id: MS:1000128
            // name: profile spectrum
            // def: "A profile mass spectrum is created when data is recorded with ion current (counts per second) on one axis and mass/charge ratio on another axis." [PSI: MS]
            // synonym: "continuous mass spectrum" EXACT []
            // synonym: "Continuum Mass Spectrum" EXACT []
            // is_a: MS:1000525 ! spectrum representation
            Profile
        }
        public int Id { get; set; } //autogenerated unique id

        /// <summary>
        /// id: MS:1003057
        /// name: scan number
        /// def: "Ordinal number of the scan indicating its order of acquisition within a mass spectrometry acquisition run." [PSI: PI]
        /// is_a: MS:1000503 ! scan attribute
        /// relationship: has_value_type xsd:integer ! The allowed value-type for this CV term
        /// </summary>
        public float ScanNumber { get; protected set; }
        /// <summary>
        /// id: MS:1000525
        /// name: spectrum representation
        /// def: "Way in which the spectrum is represented, either with regularly spaced data points or with a list of centroided peaks." [PSI: MS]
        /// relationship: part_of MS:1000442 ! spectrum
        /// </summary>
        public SpectrumRepresentationType SpectrumRepresentation { get; protected set; }



        /// <summary>
        /// id: MS:1000827
        /// name: isolation window target m/z
        /// def: "The primary or reference m/z about which the isolation window is defined." [PSI: MS]
        /// is_a: MS:1000792 ! isolation window attribute
        /// relationship: has_units MS:1000040 ! m/z
        /// relationship: has_value_type xsd:float ! The allowed value-type for this CV term
        /// </summary>
        public float IsolationWindowTargetMz { get; protected set; }
        /// <summary>
        /// id: MS:1000828
        /// name: isolation window lower offset
        /// def: "The extent of the isolation window in m/z below the isolation window target m/z. The lower and upper offsets may be asymmetric about the target m/z." [PSI: MS]
        /// is_a: MS:1000792 ! isolation window attribute
        /// relationship: has_units MS:1000040 ! m/z
        /// relationship: has_value_type xsd:float ! The allowed value-type for this CV term
        /// </summary>
        public float IsolationWindowLowerOffset { get; protected set; }
        /// <summary>
        /// id: MS:1000828
        /// name: isolation window lower offset
        /// def: "The extent of the isolation window in m/z above the isolation window target m/z. The lower and upper offsets may be asymmetric about the target m/z." [PSI: MS]
        /// is_a: MS:1000792 ! isolation window attribute
        /// relationship: has_units MS:1000040 ! m/z
        /// relationship: has_value_type xsd:float ! The allowed value-type for this CV term
        /// </summary>
        public float IsolationWindowUpperOffset { get; protected set; }


        public MsDataScanModel()
        {

        }
    }
}
