using MassSpectrometry;
using MathNet.Numerics.RootFinding;
using Microsoft.CodeAnalysis;
using MzLibUtil.NoiseEstimation;
using System;
using System.Reflection.Metadata;
using ThermoFisher.CommonCore.Data.Business;
using static MetaPAL.Models.PsiMsTypes;

namespace MetaPAL.Models
{
    public class MsDataScanModel
    {

        public int Id { get; set; } //autogenerated unique id

        /// <summary>
        /// id: MS:1003057
        /// name: scan number
        /// def: "Ordinal number of the scan indicating its order of acquisition within a mass spectrometry acquisition run." [PSI: PI]
        /// is_a: MS:1000503 ! scan attribute
        /// </summary>
        public int ScanNumber { get; protected set; }
        /// <summary>
        /// id: MS:1000525
        /// name: spectrum representation
        /// comment: can take 2 possible values: Centroid or Profile
        /// def: "Way in which the spectrum is represented, either with regularly spaced data points or with a list of centroided peaks." [PSI: MS]
        /// relationship: part_of MS:1000442 ! spectrum
        /// </summary>
        public SpectrumRepresentationType SpectrumRepresentation { get; protected set; }
        /// <summary>
        /// id: MS:1000294
        /// name: mass spectrum
        /// def: "A plot of the relative abundance of a beam or other collection of ions as a function of the mass-to-charge ratio (m/z)." [PSI: MS]
        /// is_a: MS:1000524 ! data file content
        /// is_a: MS:1000559 ! spectrum type
        /// </summary>
        public MassSpectrumType MassSpectrumType { get; protected set; }
        /// <summary>
        /// id: MS:1000511
        /// name: ms level
        /// def: "Stage number achieved in a multi stage mass spectrometry acquisition." [PSI: MS]
        /// is_a: MS:1000499 ! spectrum attribute
        /// </summary>
        public int MsLevel { get; protected set; }
        /// <summary>
        /// id: MS:1000465
        /// name: scan polarity
        /// def: "Relative orientation of the electromagnetic field during the selection and detection of ions in the mass spectrometer." [PSI: MS]
        /// relationship: part_of MS:1000441 ! scan
        /// </summary>
        public ScanPolarityType ScanPolarity { get; protected set; }
        /// <summary>
        /// id: MS:1000016
        /// name: scan start time
        /// def: "The time that an analyzer started a scan, relative to the start of the MS run." [PSI: MS]
        /// is_a: MS:1000503 ! scan attribute
        /// is_a: MS:1002345 ! PSM-level attribute
        /// relationship: has_units UO:0000010 ! second
        /// relationship: has_units UO:0000031 ! minute
        /// relationship: has_value_type xsd:float ! The allowed value-type for this CV term
        /// </summary>
        public float ScanStartTime { get; protected set; }
        /// <summary>
        /// id: MS:1000500
        /// name: scan window upper limit
        /// def: "The upper m/z bound of a mass spectrometer scan window." [PSI: MS]
        /// synonym: "mzRangeStop" RELATED[]
        /// is_a: MS:1000549 ! selection window attribute
        /// relationship: has_units MS:1000040 ! m/z
        /// </summary>
        public float ScanWindowUpperLimit { get; protected set; }
        /// <summary>
        /// id: MS:1000501re
        /// name: scan window lower limit
        /// def: "The lower m/z bound of a mass spectrometer scan window." [PSI: MS]
        /// synonym: "mzRangeStop" RELATED[]
        /// is_a: MS:1000549 ! selection window attribute
        /// relationship: has_units MS:1000040 ! m/z
        /// </summary>
        public float ScanWindowLowerLimit { get; protected set; }

        /// id: MS:1000512
        /// name: filter string
        /// def: "A string unique to Thermo instrument describing instrument settings for the scan." [PSI: MS]
        /// is_a: MS:1000503 ! scan attribute
        public string FilterString { get; protected set; }
        /// <summary>
        /// id: MS:1000443
        /// name: mass analyzer type
        /// def: "Mass analyzer separates the ions according to their mass-to-charge ratio." [PSI: MS]
        /// relationship: part_of MS:1000451 ! mass analyzer
        /// </summary>
        public MassAnalyzerType MassAnalyzerType { get; protected set; }
        /// <summary>
        /// id: MS:1000285
        /// name: total ion current
        /// def: "The sum of all the separate ion currents carried by the ions of different m/z contributing to a complete mass spectrum or in a specified m/z range of a mass spectrum." [PSI: MS]
        /// synonym: "TIC" EXACT[]
        /// is_a: MS:1003058 ! spectrum property
        /// </summary>
        public float TotalIonCurrent { get; protected set; }


        // TODO: Unclear about how to denote selected ion charge state and intensity, as there is no term for those specifically. 
        // However, there is an "ion selection attriubte" term (MS:1000455). Not sure how to organize arrange

        // TODO: There needs to be a nativeID field and a nativeID format (MS:1000767) field, but I can't find a term for the nativeID

        /// id: MS:1000927
        /// name: ion injection time
        /// def: "The length of time spent filling an ion trapping device." [PSI: MS]
        /// is_a: MS:1000503 ! scan attribute
        /// relationship: has_units UO:0000028 ! millisecond
        public float IonInjectionCurrent { get; protected set; }
        /// id: MS:1000744
        /// name: selected ion m/z
        /// def: "Mass-to-charge ratio of an selected ion." [PSI: MS]
        /// is_a: MS:1000455 ! ion selection attribute
        /// relationship: has_units MS:1000040 ! m/z
        public float SelectedIonMz { get; protected set; }

        /// <summary>
        /// id: MS:1000044
        /// name: dissociation method
        /// def: "Fragmentation method used for dissociation or fragmentation." [PSI: MS]
        /// synonym: "Activation Method" RELATED[]
        /// relationship: part_of MS:1000456 ! precursor activation
        /// </summary>
        public DissociationMethodType DissociationMethod { get; protected set; }
        /// <summary>
        /// id: MS:1000827
        /// name: isolation window target m/z
        /// def: "The primary or reference m/z about which the isolation window is defined." [PSI: MS]
        /// is_a: MS:1000792 ! isolation window attribute
        /// relationship: has_units MS:1000040 ! m/z
        /// </summary>
        public float IsolationWindowTargetMz { get; protected set; }
        /// <summary>
        /// id: MS:1000828
        /// name: isolation window lower offset
        /// def: "The extent of the isolation window in m/z below the isolation window target m/z. The lower and upper offsets may be asymmetric about the target m/z." [PSI: MS]
        /// is_a: MS:1000792 ! isolation window attribute
        /// relationship: has_units MS:1000040 ! m/z
        /// </summary>
        public float IsolationWindowLowerOffset { get; protected set; }
        /// <summary>
        /// id: MS:1000828
        /// name: isolation window lower offset
        /// def: "The extent of the isolation window in m/z above the isolation window target m/z. The lower and upper offsets may be asymmetric about the target m/z." [PSI: MS]
        /// is_a: MS:1000792 ! isolation window attribute
        /// relationship: has_units MS:1000040 ! m/z
        /// </summary>
        public float IsolationWindowUpperOffset { get; protected set; }


        public MsDataScanModel()
        {

        }
    }
}
