using System.ComponentModel.DataAnnotations;

namespace MetaPAL.Models
{
    public class ProteomicsQuantificationResult
    {
        [Key]
        public int Id { get; set; } //autogenerated unique id
    }
}
