using Easy.Common;
using MathNet.Numerics;
using Newtonsoft.Json.Linq;
using Omics.Fragmentation;
using Proteomics;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using static System.Formats.Asn1.AsnWriter;
using System.Drawing;
using System.Xml.Linq;
using ThermoFisher.CommonCore.Data.Business;

namespace MetaPAL.Models
{
    [Table("Repo")]
    public class Repo
    {
        [Key]
        public int Id { get; set; } //autogenerated unique id
        [Required]
        public string Title { get; set; } //title of the repo
        public string? Description { get; set; } //description of the repo
        public HostingRepository HostingRepository { get; set; } //hosting repository
        public string? HostingRepositoryURL { get; set; } //URL to the hosting repository
        public string? DatasetFtpLocation { get; set; }
        List<Experiment> Experiments { get; set; }

        public IEnumerable<string> RepoFeatures = new List<string>
        {
            nameof(Title),
            nameof(Description),
            nameof(HostingRepository), //problem with enums that I need to figure out
            nameof(HostingRepositoryURL),
            nameof(DatasetFtpLocation)
        };

        public Repo()
        {

        }
    }
    public enum HostingRepository
    {
        PRIDE,
        MassIVE,
        jPOST,
        Panorama,
        PeptideAtlas,
        GNPS,
        MetabolomicsWorkbench,
        Metabolights,
        Other
    }
}
