using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MetaPAL.Models;

/// <summary>
/// Model representing MetaData table for a data file
/// This will grow as more metadata is added to the database
/// Example records include
/// Organism, Human
/// Organism, Mouse
/// Instrument, Orbitrap
/// Instrument, Q-Exactive
/// DissociationType, CID
/// DissociationType, HCD
/// </summary>
[Table("SampleMetaData")]
public class SampleMetaData
{
    [Key]
    public int Id { get; set; } //autogenerated unique id
    public SampleType? Type { get; set; }
    public string? Condition { get; set; }
    public int? BiologicalReplicate { get; set; }
    public int? TechnicalReplicate { get; set; }
    public int? Fraction { get; set; }
    public string? PsmFilename { get; set; }
    public string? RawFilename { get; set; }
    public int? SamplePreparationBatch { get; set; }
    public int? LcBatchNumber { get; set; }
    public InstrumentType? Instrument { get; set; }
    public QuantificationType? Quantification { get; set; }

    public enum SampleType
    {
        SingleCell,
        CellLine,
        Tissue,
        BioFluid,
        Carrier,
        Reference,
        Empty,
        NegativeControl,
        PositiveControl,
        Other
    }

    public enum InstrumentType
    {
        Orbitrap,
        QExactive,
        Fusion,
        Lumos,
        Velos,
        LTQ,
        Other
    }

    public enum QuantificationType
    {
        LabelFree,
        TMT,
        iTRAQ,
        SILAC,
        Other
    }
}