using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MetaPAL.Models;

/// <summary>
/// Model representing MetaData table for a data file
/// This will grow as more metadata is added to the database
/// Example records include
/// Organism, Human
/// Organism, Mouse
/// Instrument, Orbitrap
/// Instrument, Q-Exactive
/// DissociationType, CID
/// DissociationType, HCD
/// </summary>
[Table("SampleMetaData")]
public class SampleMetaData
{
    [Key]
    public int Id { get; set; } //autogenerated unique id
    public SampleType? Type { get; set; }
    public string? Condition { get; set; }
    public string? PsmFilename { get; set; }
    public string? RawFilename { get; set; }
    public int? SamplePreparationBatch { get; set; }
    public int? LcBatchNumber { get; set; }
    public string? InstrumentModel { get; set; }

    public string Value { get; set; }
    public enum SampleType
    {
        SingleCell,
        CellLine,
        Tissue,
        BioFluid,
    }
}