using Omics.SpectrumMatch;

namespace MetaPAL.Models
{
    public class SpectrumMatch : SpectrumMatchFromTsv
    {
        public int Id { get; set; } //autogenerated unique id

        public SpectrumMatch()
        {
                
        }
    }
}
